services:
  database:
    container_name: database
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    image: postgres:18.0-alpine3.22
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d muse" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - database:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
  # minio:
  #   image: quay.io/minio/minio:latest
  #   container_name: minio_s3
  #   command: server /data
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - minio_data:/data
  #   ports:
  #     - "127.0.0.1:9000:9000"  # API endpoint (S3)
  #     - "127.0.0.1:9001:9001"
  #   networks:
  #     - minio_net
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3

networks:
  minio_net:
    driver: bridge

volumes:
  minio_data:
    driver: local
  database:
