// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"backend/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GenerateToken(userID string) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockAuthService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - userID string
func (_e *MockAuthService_Expecter) GenerateToken(userID interface{}) *MockAuthService_GenerateToken_Call {
	return &MockAuthService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", userID)}
}

func (_c *MockAuthService_GenerateToken_Call) Run(run func(userID string)) *MockAuthService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_GenerateToken_Call) Return(s string, err error) *MockAuthService_GenerateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_GenerateToken_Call) RunAndReturn(run func(userID string) (string, error)) *MockAuthService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyPassword(user model.User, password string) error {
	ret := _mock.Called(user, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.User, string) error); ok {
		r0 = returnFunc(user, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockAuthService_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - user model.User
//   - password string
func (_e *MockAuthService_Expecter) VerifyPassword(user interface{}, password interface{}) *MockAuthService_VerifyPassword_Call {
	return &MockAuthService_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", user, password)}
}

func (_c *MockAuthService_VerifyPassword_Call) Run(run func(user model.User, password string)) *MockAuthService_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.User
		if args[0] != nil {
			arg0 = args[0].(model.User)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyPassword_Call) Return(err error) *MockAuthService_VerifyPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_VerifyPassword_Call) RunAndReturn(run func(user model.User, password string) error) *MockAuthService_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyToken(authHeader string) (string, error) {
	ret := _mock.Called(authHeader)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(authHeader)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(authHeader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(authHeader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockAuthService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - authHeader string
func (_e *MockAuthService_Expecter) VerifyToken(authHeader interface{}) *MockAuthService_VerifyToken_Call {
	return &MockAuthService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", authHeader)}
}

func (_c *MockAuthService_VerifyToken_Call) Run(run func(authHeader string)) *MockAuthService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyToken_Call) Return(s string, err error) *MockAuthService_VerifyToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_VerifyToken_Call) RunAndReturn(run func(authHeader string) (string, error)) *MockAuthService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
